app:

  server:
    host: "0.0.0.0"
    port: "50051"
    shutdown_timeout: 5s
    auth_token: "secret"

  node:
    url: "https://testnet.tonapi.io" # https://tonapi.io - mainnet node url, replace if needed
    api_key: "YOUR-API-KEY"
    timeout: 10s
    rate_limit: 1
    rate_burst: 5

