apiVersion: apps/v1
kind: Deployment
metadata:
  name: ton-node-service
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ton-node-service
  template:
    metadata:
      labels:
        app: ton-node-service
    spec:
      containers:
        - name: ton-node-service
          image: registry.localhost:5001/ton-node-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
          livenessProbe:
            httpGet:
              path: /ping
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: ton-node-config
