apiVersion: apps/v1
kind: Deployment
metadata:
  name: ton-node-prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ton-node-prometheus
  template:
    metadata:
      labels:
        app: ton-node-prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
            - containerPort: 9091
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
