apiVersion: v1
kind: Service
metadata:
  name: ton-node-prometheus
  namespace: monitoring
spec:
  selector:
    app: ton-node-prometheus
  ports:
    - name: "prometheus-ui"
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30091
  type: NodePort
