name: Deployment TON-Node

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install protoc-gen-go
        run: |
          GO111MODULE=on go get google.golang.org/protobuf/cmd/protoc-gen-go
          GO111MODULE=on go get google.golang.org/grpc/cmd/protoc-gen-go-grpc

      - name: Add Go bin to PATH
        run: echo "::add-path::$(go env GOPATH)/bin"

      - name: Setup config
        run: make -B setup

      - name: Replace API Key
        run: |
          sed -i 's/api_key: ".*"/api_key: "${{ secrets.TON_API_KEY }}"/' config.yaml

      - name: Generate proto
        run: make -B proto

      - name: Run lint
        run: make -B lint-fix

      - name: Run tests
        run: make -B tests

      - name: Build in docker
        run: make docker_run
